# -*- coding: utf-8 -*-
"""lab6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_BROuu1i7DJD2Ripapw9GHSgIammN4NB
"""

SAVED_MODEL_FILENAME = "saved_model.keras"  #Fix 1: save the model using .keras format instead of .h5 (.h5 is getting depreciated)
FLOAT_TFL_MODEL_FILENAME = "float_model.tfl"
QUANTIZED_TFL_MODEL_FILENAME = "quantized_model.tfl"
TFL_CC_MODEL_FILENAME = "magic_wand_model_data.cc"

# ~ from google.colab import drive
# ~ drive.mount('/content/drive')
# ~ !unzip /content/drive/MyDrive/eep564/magic_wand_digit_data.zip
# ~ !mv magic_wand_digit_data-* magic_wand_digit_data
# ~ !mkdir -p checkpoints
import os
from pathlib import Path
import tensorflow as tf
from pathlib import Path
# specify tarball in local fs
dataset_url = "file://" + os.path.abspath("./magic_wand_digit_data.zip")
ds_name = "magicwand-data"
archive = tf.keras.utils.get_file(fname=ds_name, origin=dataset_url, extract=True)
data_dir = Path(archive).parent
ds_home = Path.home().joinpath(".keras/datasets")
assert data_dir==ds_home, "expect that ds is extracted under ~/.keras/dataset"

print(Path(archive))
jsonpath = Path(archive).joinpath("magic_wand_digit_data/*.json")
print(jsonpath)

import glob
import json
strokes = []
for filename in glob.glob( str(jsonpath) ):
  with open(filename, "r") as file:
    file_contents = file.read()
  file_data = json.loads(file_contents)
  for stroke in file_data["strokes"]:
    stroke["filename"] = filename
    strokes.append(stroke)

import matplotlib.pyplot as plt

def plot_stroke(stroke):

  x_array = []
  y_array = []
  for coords in stroke["strokePoints"]:
    x_array.append(coords["x"])
    y_array.append(coords["y"])

  fig = plt.figure(figsize=(12.8, 4.8))
  fig.suptitle(stroke["label"])

  ax = fig.add_subplot(131)
  ax.set_xlabel('x')
  ax.set_ylabel('y')
  ax.set_xlim(-0.4, 0.4)
  ax.set_ylim(-0.4, 0.4)
  ax.plot(x_array, y_array)

  plt.show()

plot_stroke(strokes[11])

import math
import numpy as np
import PIL

FIXED_POINT = 256

def mul_fp(a, b):
  return (a * b) / FIXED_POINT

def div_fp(a, b):
  if b == 0:
    b = 1
  return (a * FIXED_POINT) / b

def float_to_fp(a):
  return math.floor(a * FIXED_POINT)

def norm_to_coord_fp(a, range_fp, half_size_fp):
  a_fp = float_to_fp(a)
  norm_fp = div_fp(a_fp, range_fp)
  return mul_fp(norm_fp, half_size_fp) + half_size_fp

def round_fp_to_int(a):
  return math.floor((a + (FIXED_POINT / 2)) / FIXED_POINT)

def gate(a, min, max):
  if a < min:
    return min
  elif a > max:
    return max
  else:
    return a

def rasterize_stroke(stroke_points, x_range, y_range, width, height):
  num_channels = 3
  buffer_byte_count = height * width * num_channels
  buffer = bytearray(buffer_byte_count)

  width_fp = width * FIXED_POINT
  height_fp = height * FIXED_POINT
  half_width_fp = width_fp / 2
  half_height_fp = height_fp / 2
  x_range_fp = float_to_fp(x_range)
  y_range_fp = float_to_fp(y_range)

  t_inc_fp = FIXED_POINT / len(stroke_points)

  one_half_fp = (FIXED_POINT / 2)

  for point_index in range(len(stroke_points) - 1):
    start_point = stroke_points[point_index]
    end_point = stroke_points[point_index + 1]
    start_x_fp = norm_to_coord_fp(start_point["x"], x_range_fp, half_width_fp)
    start_y_fp = norm_to_coord_fp(-start_point["y"], y_range_fp, half_height_fp)
    end_x_fp = norm_to_coord_fp(end_point["x"], x_range_fp, half_width_fp)
    end_y_fp = norm_to_coord_fp(-end_point["y"], y_range_fp, half_height_fp)
    delta_x_fp = end_x_fp - start_x_fp
    delta_y_fp = end_y_fp - start_y_fp

    t_fp = point_index * t_inc_fp
    if t_fp < one_half_fp:
      local_t_fp = div_fp(t_fp, one_half_fp)
      one_minus_t_fp = FIXED_POINT - local_t_fp
      red = round_fp_to_int(one_minus_t_fp * 255)
      green = round_fp_to_int(local_t_fp * 255)
      blue = 0
    else:
      local_t_fp = div_fp(t_fp - one_half_fp, one_half_fp)
      one_minus_t_fp = FIXED_POINT - local_t_fp
      red = 0
      green = round_fp_to_int(one_minus_t_fp * 255)
      blue = round_fp_to_int(local_t_fp * 255)
    red = gate(red, 0, 255)
    green = gate(green, 0, 255)
    blue = gate(blue, 0, 255)

    if abs(delta_x_fp) > abs(delta_y_fp):
      line_length = abs(round_fp_to_int(delta_x_fp))
      if delta_x_fp > 0:
        x_inc_fp = 1 * FIXED_POINT
        y_inc_fp = div_fp(delta_y_fp, delta_x_fp)
      else:
        x_inc_fp = -1 * FIXED_POINT
        y_inc_fp = -div_fp(delta_y_fp, delta_x_fp)
    else:
      line_length = abs(round_fp_to_int(delta_y_fp))
      if delta_y_fp > 0:
        y_inc_fp = 1 * FIXED_POINT
        x_inc_fp = div_fp(delta_x_fp, delta_y_fp)
      else:
        y_inc_fp = -1 * FIXED_POINT
        x_inc_fp = -div_fp(delta_x_fp, delta_y_fp)
    for i in range(line_length + 1):
      x_fp = start_x_fp + (i * x_inc_fp)
      y_fp = start_y_fp + (i * y_inc_fp)
      x = round_fp_to_int(x_fp)
      y = round_fp_to_int(y_fp)
      if (x < 0) or (x >= width) or (y < 0) or (y >= height):
        continue
      buffer_index = (y * width * num_channels) + (x * num_channels)
      buffer[buffer_index + 0] = red
      buffer[buffer_index + 1] = green
      buffer[buffer_index + 2] = blue

  np_buffer = np.frombuffer(buffer, dtype=np.uint8).reshape(height, width, num_channels)

  return np_buffer

raster = rasterize_stroke(strokes[11]["strokePoints"], 0.5, 0.5, 32, 32)
PIL.Image.fromarray(raster).resize((512, 512), PIL.Image.NEAREST)

from pathlib import Path
import shutil

X_RANGE = 0.6
Y_RANGE = 0.6

def ensure_empty_dir(dirname):
  dirpath = Path(dirname)
  if dirpath.exists() and dirpath.is_dir():
    shutil.rmtree(dirpath)
  dirpath.mkdir()

def augment_points(points, move_range, scale_range, rotate_range):
  move_x = np.random.uniform(low=-move_range, high=move_range)
  move_y = np.random.uniform(low=-move_range, high=move_range)
  scale = np.random.uniform(low=1.0-scale_range, high=1.0+scale_range)
  rotate = np.random.uniform(low=-rotate_range, high=rotate_range)

  x_axis_x = math.cos(rotate) * scale
  x_axis_y = math.sin(rotate) * scale

  y_axis_x = -math.sin(rotate) * scale
  y_axis_y = math.cos(rotate) * scale

  new_points = []
  for point in points:
    old_x = point["x"]
    old_y = point["y"]
    new_x = (x_axis_x * old_x) + (x_axis_y * old_y) + move_x
    new_y = (y_axis_x * old_x) + (y_axis_y * old_y) + move_y
    new_points.append({"x": new_x, "y": new_y})

  return new_points

def save_strokes_as_images(strokes, root_folder, width, height, augment_count):
  ensure_empty_dir(root_folder)
  labels = set()
  for stroke in strokes:
    labels.add(stroke["label"].lower())
  for label in labels:
    label_path = Path(root_folder, label)
    ensure_empty_dir(label_path)

  label_counts = {}
  for stroke in strokes:
    points = stroke["strokePoints"]
    label = stroke["label"].lower()
    if label == "":
      raise Exception("Missing label for %s:%d" % (stroke["filename"], stroke["index"]))
    if label not in label_counts:
      label_counts[label] = 0
    label_count = label_counts[label]
    label_counts[label] += 1
    raster = rasterize_stroke(points, X_RANGE, Y_RANGE, width, height)
    image = PIL.Image.fromarray(raster)
    image.save(Path(root_folder, label, str(label_count) + ".png"))
    for i in range(augment_count):
      augmented_points = augment_points(points, 0.1, 0.1, 0.3)
      raster = rasterize_stroke(augmented_points, X_RANGE, Y_RANGE, width, height)
      image = PIL.Image.fromarray(raster)
      image.save(Path(root_folder, label, str(label_count) + "_a" + str(i) + ".png"))

IMAGE_WIDTH = 32
IMAGE_HEIGHT = 32

shuffled_strokes = strokes
np.random.shuffle(shuffled_strokes)

test_percentage = 10
validation_percentage = 10
train_percentage = 100 - (test_percentage + validation_percentage)

test_count = math.floor((len(shuffled_strokes) * test_percentage) / 100)
validation_count = math.floor((len(shuffled_strokes) * validation_percentage) / 100)
test_strokes = shuffled_strokes[0:test_count]
validation_strokes = shuffled_strokes[test_count:(test_count + validation_count)]
train_strokes = shuffled_strokes[(test_count + validation_count):]

save_strokes_as_images(test_strokes, "test", IMAGE_WIDTH, IMAGE_HEIGHT, 10)
save_strokes_as_images(validation_strokes, "validation", IMAGE_WIDTH, IMAGE_HEIGHT, 0)
save_strokes_as_images(train_strokes, "train", IMAGE_WIDTH, IMAGE_HEIGHT, 10)

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.utils import image_dataset_from_directory

validation_ds = image_dataset_from_directory(
    directory='validation',
    labels='inferred',
    label_mode='categorical',
    batch_size=32,
    image_size=(IMAGE_WIDTH, IMAGE_HEIGHT)).prefetch(buffer_size=32)

# train_ds = image_dataset_from_directory(
    # directory='train',
    # labels='inferred',
    # label_mode='categorical',
    # batch_size=32,
    # image_size=(IMAGE_WIDTH, IMAGE_HEIGHT)).prefetch(buffer_size=32)

# import matplotlib.pyplot as plt

# plt.figure(figsize=(10, 10))
# for images, labels in train_ds.take(1):
  # for i in range(9):
    # ax = plt.subplot(3, 3, i + 1)
    # plt.imshow(images[i].numpy().astype("uint8"))
    # plt.axis("off")

# from keras import layers

# def make_model(input_shape, num_classes):
    # inputs = keras.Input(shape=input_shape)

    # # Entry block
    # x = layers.Rescaling(1.0 / 255)(inputs)
    # x = layers.Conv2D(16, 3, strides=2, padding="same")(x)
    # x = layers.BatchNormalization()(x)
    # x = layers.Activation("relu")(x)
    # x = layers.Dropout(0.5)(x)

    # x = layers.Conv2D(32, 3, strides=2, padding="same")(x)
    # x = layers.BatchNormalization()(x)
    # x = layers.Activation("relu")(x)
    # x = layers.Dropout(0.5)(x)

    # x = layers.Conv2D(64, 3, strides=2, padding="same")(x)
    # x = layers.BatchNormalization()(x)
    # x = layers.Activation("relu")(x)
    # x = layers.Dropout(0.5)(x)

    # x = layers.GlobalAveragePooling2D()(x)
    # activation = "softmax"
    # units = num_classes

    # x = layers.Dropout(0.5)(x)
    # outputs = layers.Dense(units, activation=activation)(x)
    # return keras.Model(inputs, outputs)

# model = make_model(input_shape=(IMAGE_WIDTH, IMAGE_HEIGHT, 3), num_classes=10)
# keras.utils.plot_model(model, show_shapes=True)

# epochs = 30

# #<-------- Fix: Keras now expects model files to end with .keras, which is the updated format.
# #               This ensures the model saves correctly and prevents the ValueError.
# callbacks = [
    # keras.callbacks.ModelCheckpoint("checkpoints/save_at_{epoch}.keras"),
# ]


# model.compile(
    # optimizer=keras.optimizers.Adam(1e-3),
    # loss="binary_crossentropy",
    # metrics=["accuracy"],
# )
# model.fit(
    # train_ds, epochs=epochs, callbacks=callbacks, validation_data=validation_ds,
# )

# def predict_image(model, filename):
  # img = keras.preprocessing.image.load_img(filename, target_size=(IMAGE_WIDTH, IMAGE_HEIGHT))
  # img_array = keras.preprocessing.image.img_to_array(img)
  # img_array = tf.expand_dims(img_array, 0)  # Create batch axis
  # predictions = model.predict(img_array).flatten()
  # predicted_label_index = np.argmax(predictions)
  # predicted_score = predictions[predicted_label_index]
  # return (predicted_label_index, predicted_score)

# index, score = predict_image(model, "test/7/2.png")

# print(index, score)

# from IPython.display import Image, display

# SCORE_THRESHOLD = 0.75

# correct_count = 0
# wrong_count = 0
# discarded_count = 0
# for label_dir in glob.glob("test/*"):
  # label = int(label_dir.replace("test/", ""))
  # for filename in glob.glob(label_dir + "/*.png"):
    # index, score = predict_image(model, filename)
    # if score < SCORE_THRESHOLD:
      # discarded_count += 1
      # continue
    # if index == label:
      # correct_count += 1
    # else:
      # wrong_count += 1
      # print("%d expected, %d found with score %f" % (label, index, score))
      # display(Image(filename=filename))

# correct_percentage = (correct_count / (correct_count + wrong_count)) * 100
# print("%.1f%% correct (N=%d, %d unknown)" % (correct_percentage, (correct_count + wrong_count), discarded_count))

# model.save(SAVED_MODEL_FILENAME)

# #!curl -L https://storage.googleapis.com/download.tensorflow.org/models/tflite/micro/magic_wand_saved_model_2021_01_02.tgz -o saved_model.tgz
# #!tar -xzf saved_model.tgz

# # Fix 2: Load the Keras model from the .keras file
# loaded_model = tf.keras.models.load_model(SAVED_MODEL_FILENAME)
# # Fix 3: Convert the model to TensorFlow Lite format using "from_keras_model"
# converter = tf.lite.TFLiteConverter.from_keras_model(loaded_model)
# model_no_quant_tflite = converter.convert()

# # Save the model to disk
# open(FLOAT_TFL_MODEL_FILENAME, "wb").write(model_no_quant_tflite)

# def representative_dataset():
  # for filename in glob.glob("test/*/*.png"):
    # img = keras.preprocessing.image.load_img(filename, target_size=(IMAGE_WIDTH, IMAGE_HEIGHT))
    # img_array = keras.preprocessing.image.img_to_array(img)
    # img_array = tf.expand_dims(img_array, 0)  # Create batch axis      for images, labels in train_ds.take(1):
    # yield([img_array])
# # Set the optimization flag.
# converter.optimizations = [tf.lite.Optimize.DEFAULT]
# # Enforce integer only quantization
# converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
# converter.inference_input_type = tf.int8
# converter.inference_output_type = tf.int8
# # Provide a representative dataset to ensure we quantize correctly.
# converter.representative_dataset = representative_dataset
# model_tflite = converter.convert()

# # Save the model to disk
# open(QUANTIZED_TFL_MODEL_FILENAME, "wb").write(model_tflite)

# def predict_tflite(tflite_model, filename):
  # img = keras.preprocessing.image.load_img(filename, target_size=(IMAGE_WIDTH, IMAGE_HEIGHT))
  # img_array = keras.preprocessing.image.img_to_array(img)
  # img_array = tf.expand_dims(img_array, 0)

  # # Initialize the TFLite interpreter
  # interpreter = tf.lite.Interpreter(model_content=tflite_model)
  # interpreter.allocate_tensors()

  # input_details = interpreter.get_input_details()[0]
  # output_details = interpreter.get_output_details()[0]

  # # If required, quantize the input layer (from float to integer)
  # input_scale, input_zero_point = input_details["quantization"]
  # if (input_scale, input_zero_point) != (0.0, 0):
    # img_array = np.multiply(img_array, 1.0 / input_scale) + input_zero_point
    # img_array = img_array.astype(input_details["dtype"])

  # # Invoke the interpreter
  # interpreter.set_tensor(input_details["index"], img_array)
  # interpreter.invoke()
  # pred = interpreter.get_tensor(output_details["index"])[0]

  # # If required, dequantized the output layer (from integer to float)
  # output_scale, output_zero_point = output_details["quantization"]
  # if (output_scale, output_zero_point) != (0.0, 0):
    # pred = pred.astype(np.float32)
    # pred = np.multiply((pred - output_zero_point), output_scale)

  # predicted_label_index = np.argmax(pred)
  # predicted_score = pred[predicted_label_index]
  # return (predicted_label_index, predicted_score)

# predict_tflite(model_no_quant_tflite, "test/7/2.png")

# predict_tflite(model_tflite, "test/7/2.png")

# from IPython.display import Image, display

# correct_count = 0
# wrong_count = 0
# discarded_count = 0
# for label_dir in glob.glob("test/*"):
  # label = int(label_dir.replace("test/", ""))
  # for filename in glob.glob(label_dir + "/*.png"):
    # index, score = predict_tflite(model_tflite, filename)
    # if score < 0.75:
      # discarded_count += 1
      # continue
    # if index == label:
      # correct_count += 1
    # else:
      # wrong_count += 1
      # print("%d expected, %d found with score %f" % (label, index, score))
      # display(Image(filename=filename))

# correct_percentage = (correct_count / (correct_count + wrong_count)) * 100

# print("%.1f%% correct (N=%d, %d unknown)" % (correct_percentage, (correct_count + wrong_count), discarded_count))

# # Fix 4:  use os.path.getsize() for files like .keras or .h5, since these are individual files, not directories.

# import os
# import pandas as pd

# # Function to calculate directory size (for future use with directories)
# def get_dir_size(dir):
    # size = 0
    # for f in os.scandir(dir):
        # if f.is_file():
            # size += f.stat().st_size
        # elif f.is_dir():
            # size += get_dir_size(f.path)
    # return size

# # Calculate size of individual files
# size_tf = os.path.getsize(SAVED_MODEL_FILENAME)  # Use os.path.getsize for files
# size_no_quant_tflite = os.path.getsize(FLOAT_TFL_MODEL_FILENAME)
# size_tflite = os.path.getsize(QUANTIZED_TFL_MODEL_FILENAME)

# # Compare size
# df = pd.DataFrame.from_records(
    # [["TensorFlow", f"{size_tf} bytes", ""],
     # ["TensorFlow Lite", f"{size_no_quant_tflite} bytes", f"(reduced by {size_tf - size_no_quant_tflite} bytes)"],
     # ["TensorFlow Lite Quantized", f"{size_tflite} bytes", f"(reduced by {size_no_quant_tflite - size_tflite} bytes)"]],
    # columns=["Model", "Size", "Reduction"], index=["Model"])

# # Display the dataframe
# print(df)

# # Install xxd if it is not available
# !apt-get update && apt-get -qq install xxd
# # Convert to a C source file, i.e, a TensorFlow Lite for Microcontrollers model
# !xxd -i {QUANTIZED_TFL_MODEL_FILENAME} > {TFL_CC_MODEL_FILENAME}
# # Update variable names
# REPLACE_TEXT = QUANTIZED_TFL_MODEL_FILENAME.replace('/', '_').replace('.', '_')
# !sed -i 's/'{REPLACE_TEXT}'/g_magic_wand_model_data/g' {TFL_CC_MODEL_FILENAME}

# # Print the C source file
# !tail {TFL_CC_MODEL_FILENAME}
