# -*- coding: utf-8 -*-
"""EE564_TinyML_Spring25_HW1_StudentVersion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U8PS9Lpp-2Z3XSDiEiigln_6OwvrDCuu
"""

# ~ !pip uninstall -y keras tensorflow tensorflow-model-optimization
# ~ !pip install tensorflow==2.12 tensorflow-model-optimization

# ============================
# Set backend early
# ============================
import os
os.environ["KERAS_BACKEND"] = "tensorflow"

# ============================
# Import libraries
# ============================
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report, confusion_matrix, r2_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import Input, Model

import tensorflow_model_optimization as tfmot

"""

---


# Problem 1"""

# Load dataset
column_names = [
    'Class', 'Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash', 'Magnesium',
    'Total phenols', 'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins',
    'Color intensity', 'Hue', 'OD280/OD315 of diluted wines', 'Proline'
]
# ~ df = pd.read_csv('wine.data', header=None, names=column_names)
from pathlib import Path
# specify tarball in local fs
dataset_url = "file://" + os.path.abspath("./wine.data")
ds_name = "wine-data"
archive = tf.keras.utils.get_file(fname=ds_name, origin=dataset_url, extract=False)
data_dir = Path(archive).parent
ds_home = Path.home().joinpath(".keras/datasets")
assert data_dir==ds_home, "expect that ds is extracted under ~/.keras/dataset"
df = pd.read_csv(archive, header=None, names=column_names)


# Number of classes
num_classes = df['Class'].nunique()
print("Number of classes:", num_classes)

# Number of features (excluding the class label)
num_features = df.shape[1] - 1
print("Number of features:", num_features)

# Basic stats: min, max, mean, std
feature_stats = df.describe().T[['min', 'max', 'mean', 'std']]
print("\nFeature statistics:\n", feature_stats)

# Class distribution
class_counts = df['Class'].value_counts().sort_index()
print("\nClass distribution:\n", class_counts)

"""## Problem 1 - Part (a)
### Base Model Training and Evaluation

"""

# Step 1: Drop the 'Class' column from the feature set and store it separately
# - Assign features to variable X
# - Subtract 1 from class labels to convert them to 0-based indexing
# - Assign class labels to variable y

X = df.drop(["Class"], axis=1).values
y = df["Class"].sub(1).values

# Step 2: Perform a train-test split (70% train, 30% test) using random_state=42

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# print(X_train.shape)
# print(X_test.shape)

# Step 3: Use StandardScaler to normalize the features
# - Fit on X_train and transform both X_train and X_test

X_train_norm = StandardScaler().fit_transform(X_train)
X_test_norm = StandardScaler().fit_transform(X_test)

# Step 4: Use one-hot encoding for y_train and y_test
# - Use keras.utils.to_categorical

y_train_ohenc = to_categorical(y_train)
y_test_ohenc = to_categorical(y_test)

# Step 5: Define a Sequential model with the following architecture:
# - Dense(64, relu)
# - Dense(32, relu)
# - Dense(3, softmax)  # 3-class classification

model = Sequential(
    [
        Dense(64, activation="relu"),
        Dense(32, activation="relu"),
        Dense(3, activation="softmax"),
    ]
)

# Step 6: Compile using Adam optimizer, categorical_crossentropy loss, and accuracy metric
# - Train for 20 epochs with batch_size=8 and validation_split=0.2

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history = model.fit(X_train_norm, y_train_ohenc, epochs=20, batch_size=8, validation_split=0.2)

# Step 7: Evaluate the model on test data and print:
# - Accuracy
# - Classification report
# - Confusion matrix

baseline_accuracy = model.evaluate(X_test_norm, y_test_ohenc, verbose=0)[1]
print(f"Baseline Model Accuracy: {baseline_accuracy:.4f}")
predictions = model.predict(X_test_norm)
# Convert predictions to class labels (0, 1, or 2)
predicted_labels = np.argmax(predictions, axis=1) 
# Convert y_test_ohenc back to class labels if necessary
true_labels = np.argmax(y_test_ohenc, axis=1)
print("Classification report:")
print(classification_report(true_labels, predicted_labels))
print("Confusion matrix:")
print(confusion_matrix(true_labels, predicted_labels))

# Step 8: Convert the trained model to TFLite format and save it as "model_base.tflite"
# - Print the file size in kilobytes

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
with open("model_base.tflite", "wb") as f:
    f.write(tflite_model)

print(f"model_base.tflite: {os.path.getsize('model_base.tflite') / 1024:.2f} KB")

"""## Problem 1 - Part (b)

### Quantization (int8, float16, dynamic range)

"""
def representative_data_gen():
    for input_value in X_train_norm[:100]:
        yield [input_value.astype("float32")]

def quantize_and_evaluate(model, X_test, y_test_cat, quant_type, filename):
    # Create the TFLite converter from the trained Keras model
    converter = tf.lite.TFLiteConverter.from_keras_model(model)

    # Set supported ops
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS,
        tf.lite.OpsSet.SELECT_TF_OPS
    ]
    converter._experimental_lower_tensor_list_ops = False

    # Step 1: Apply quantization settings
    if quant_type == 'int8':
        # (a) Enable default optimizations
        # (b) Define a representative dataset generator (e.g., first 100 samples from X_train_scaled)
        # (c) Set inference_input_type and inference_output_type to tf.int8
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.representative_dataset = representative_data_gen
        converter.target_spec.supported_types = [tf.int8]
        converter.inference_input_type = tf.int8
        converter.inference_output_type = tf.int8

    elif quant_type == 'float16':
        # (a) Enable default optimizations
        # (b) Set supported_types to [tf.float16]
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.target_spec.supported_types = [tf.float16]

    elif quant_type == 'dynamic':
        # (a) Enable default optimizations
        converter.optimizations = [tf.lite.Optimize.DEFAULT]


    # Step 2: Convert the model and save it to the provided filename

    tflite_model_out = converter.convert()
    with open(filename, "wb") as f:
        f.write(tflite_model_out)

    # Step 3: Run Inference
    # Complete the following:
    # - Use tf.lite.Interpreter to load the TFLite model
    # - Allocate tensors
    # - Get input/output tensor details
    # - If input is quantized (dtype=int8), quantize test input accordingly
    # - If output is quantized (dtype=int8), dequantize predictions
    # - Collect predictions into y_pred (use np.argmax to get class index)
    # - Compare with y_true = np.argmax(y_test_cat, axis=1)

    interpreter = tf.lite.Interpreter(model_path=filename)
    interpreter.allocate_tensors()

    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    input_dtype = input_details[0]['dtype']
    input_scale, input_zero_point = input_details[0]['quantization']
    output_dtype = output_details[0]['dtype']


    coll_preds = []
    for i in range(len(X_test)):
        input_data = X_test[i:i+1].astype("float32")

        # Quantize if necessary
        if input_dtype == np.int8:
            input_data = input_data / input_scale + input_zero_point
            input_data = np.round(input_data).astype(np.int8)

        interpreter.set_tensor(input_details[0]['index'], input_data)
        interpreter.invoke()
        # ~ # # deQuantize if necessary
        # ~ # if output_dtype == np.int8:
        output_data = interpreter.get_tensor(output_details[0]['index'])
        coll_preds.append(output_data[0]) # Get the first element of the prediction output

    # Step 4: Report results
    print(f"\n📦 {quant_type.upper()} TFLite Model Size: {os.path.getsize(filename) / 1024:.2f} KB")
    y_pred = np.argmax(coll_preds, axis=1) 
    y_true = np.argmax(y_test_cat, axis=1)
    print(f"{quant_type.upper()} Classification report:")
    print(classification_report(y_true, y_pred))
    print(f"{quant_type.upper()} Confusion matrix:")
    print(confusion_matrix(y_true, y_pred))

# Step 5: Use the function above to create and evaluate three quantized models:
# - 'int8' → save as 'model_int8.tflite'
# - 'float16' → save as 'model_float16.tflite'
# - 'dynamic' → save as 'model_dynamic.tflite'

quantize_and_evaluate(model, X_test_norm, y_test_ohenc, 'int8', 'model_int8.tflite')
quantize_and_evaluate(model, X_test_norm, y_test_ohenc, 'float16', 'model_float16.tflite')
quantize_and_evaluate(model, X_test_norm, y_test_ohenc, 'dynamic', 'model_dynamic.tflite')


# """## Problem 1 - Part (c)

# ### Pruning
# """

# Step 1: Define a pruning schedule using tfmot.sparsity.keras.PolynomialDecay
# HINT:
# - Use initial_sparsity = 0.5 and final_sparsity = 0.7
# - Set end_step to total training steps (approx. dataset_size / batch_size * epochs)

prune_low_magnitude = tfmot.sparsity.keras.prune_low_magnitude
# Compute end step to finish pruning after 20 epochs.
batch_size = 8
epochs = 20
validation_split = 0.2 # 20% of training set will be used for validation set. 

num_images = X_train.shape[0] * (1 - validation_split)
end_step = np.ceil(num_images / batch_size).astype(np.int32) * epochs

pruning_params = {
    'pruning_schedule': tfmot.sparsity.keras.PolynomialDecay(
        initial_sparsity=0.5,
        final_sparsity=0.7,
        begin_step=0,
        end_step=end_step
    )
}

# Step 2: Build a Sequential model with 3 pruned Dense layers:
# - Dense(64, relu)
# - Dense(32, relu)
# - Dense(3, softmax)
# Make sure each Dense layer is wrapped with prune_low_magnitude()

model_to_prune = Sequential(
    [
        Input(shape=(X_train.shape[1],)),
        prune_low_magnitude(Dense(64, activation="relu"), **pruning_params),
        prune_low_magnitude(Dense(32, activation="relu"), **pruning_params),
        prune_low_magnitude(Dense(3, activation="softmax"), **pruning_params),

    ]
)

# Step 3: Compile the model with categorical_crossentropy and accuracy
# - Train for 10 epochs with batch_size=8 and validation_split=0.2
# - Add tfmot.sparsity.keras.UpdatePruningStep() to the callbacks list
callbacks = [tfmot.sparsity.keras.UpdatePruningStep()]
model_to_prune.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model_to_prune.fit(
    X_train_norm,
    y_train_ohenc,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=validation_split,
    callbacks=callbacks  # Add the required callback
)
model_to_prune.summary()

# Step 4: Do any necessary post-processing (if needed) on the pruned model
# and save it using appropriate specifications to a TFLite file named "model_pruned.tflite".
# Print the final file size in KB.

# <-- Enter your code here <--#

# # Step 5: Evaluate using the stripped model
# # - Use np.argmax for predictions
# # - Print classification_report and confusion_matrix

# # <-- Enter your code here <--#

# """## Problem 1 - Part (d)

# ### Knowledge Distillation
# """

# # Step 1: Define a Sequential model for Student with:
# # - Dense(32, relu)
# # - Dense(16, relu)
# # - Dense(3, softmax)

# # <-- Enter your code here <--#

# # Step 2: Use model.predict() on X_train_scaled to obtain teacher soft labels

# # <-- Enter your code here <--#

# # Step 3:
# # (a) Concatenate hard (y_train_cat) and soft (teacher_preds_soft) labels along axis=1
# #     to create a combined label for distillation
# # (b) Define a custom distillation_loss() function that:
# #     - Splits y_true_combined into y_true_hard and y_true_soft
# #     - Computes two losses (both using categorical_crossentropy)
# #     - Combines them with a weight factor alpha = 0.5

# # Hint: Use slicing [:, :3] and [:, 3:] to split the combined labels

# # <-- Enter your code here <--#

# def distillation_loss(y_true_combined, y_pred):

    # # <-- Enter your code here: implement hard/soft label separation and weighted loss <--#
    # pass

# # Step 4: Compile the student model with Adam optimizer and distillation_loss
# # - Train for 10 epochs, batch_size=8, validation_split=0.2

# # <-- Enter your code here <--#

# # Step 5: Convert the student model to TFLite
# # - Use appropriate settings for classification models
# # - Save as "model_kd.tflite"
# # - Print the file size in KB

# # <-- Enter your code here <--#

# # Step 7: Use student_model.predict() to obtain predictions on X_test_scaled
# # - Print classification_report and confusion_matrix

# # <-- Enter your code here <--#

# """## Problem 1 - Part (e)

# ### Possibility of Further Model Size Reduction

# Can you **further reduce the model size** beyond the smallest model obtained in parts **(b)**, **(c)**, or **(d)**, **without sacrificing significant classification performance**?

# Your task is to:

# 1. **Analyze and compare** the results from previous parts: Which model had the smallest size? Which performed best?

# 2. **Propose a strategy** that combines or enhances techniques learned so far.

# 3. **Implement** your proposed solution.

# 4. **Evaluate** the resulting model using both:
   # - TFLite model size (in KB)
   # - Classification performance (accuracy and report)

# 5. **Justify your results:**
   # - If further size reduction is **not** possible without major loss of accuracy, explain why using evidence from your experiments.
   # - If you succeed in reducing the size **further**, highlight what change made the biggest difference.

# """

# # <-- Justify your answer and if needed enter your code here <--#

# """

# ---


# # Problem 2"""

# # Load dataset
# df = pd.read_csv("AirQualityUCI.csv", sep=";", decimal=",", skipfooter=1, engine="python")
# df = df.drop(columns=["Unnamed: 15", "Unnamed: 16"])
# df["Datetime"] = pd.to_datetime(df["Date"] + " " + df["Time"], format="%d/%m/%Y %H.%M.%S")
# df = df.drop(columns=["Date", "Time"])
# for col in df.columns:
    # if df[col].dtype == 'object':
        # df[col] = df[col].str.replace(',', '.').astype(float)
# df.dropna(inplace=True)

# # Number of data columns (excluding the Date Time column)
# num_cols = df.shape[1]
# print("Number of columns:", num_cols)

# # Basic stats: min, max, mean, std
# col_stats = df.describe().T[['min', 'max', 'mean', 'std']]
# print("\nColumn statistics:\n", col_stats)

# """## Problem 2 - Part (a)
# ### Base Model Training and Evaluation
# """

# # Step 1: Drop the 'Datetime' column and scale all remaining features to [0, 1]

# # <-- Enter your code here <--#

# # Step 2: Implement create_sequences_all_to_all(data, seq_length) function
# # - Output shape of X should be (num_sequences, 24, num_features)
# # - Output shape of y should be (num_sequences, num_features)
# # HINTs:
# # Function should generate sequences of length 24, where:
# #     - Each input sequence X[i] is a 24-time-step window
# #     - The corresponding label y[i] is the value of all features at time step i + 24

# # <-- Enter your code here <--#

# # Step 3: Perform an 80/20 train-test split

# # <-- Enter your code here <--#

# # Step 4: Build, Compile, and Train the LSTM model
# # - Create a Keras Sequential model with:
# #     - LSTM(64, relu)
# #     - Dense(32, relu)
# #     - Dense(output_dim = number of features)
# # - Use 'adam' optimizer and 'mse' loss
# # - Train for 10 epochs with batch_size=32 and validation_split=0.1

# # <-- Enter your code here <--#

# # Step 5: Evaluate model using r2_score
# # - Print overall R² and per-feature R²
# # - Use model.predict() on X_test

# # <-- Enter your code here <--#

# # Step 6: Convert and save the trained model to TFLite using float32 precision
# # - Use TFLITE_BUILTINS and SELECT_TF_OPS
# # - Save as 'model_float32.tflite'
# # - Print model size

# # <-- Enter your code here <--#

# """## Problem 2 - Part (b)

# ### Quantization (int8, float16, dynamic range)
# """

# def convert_and_evaluate(model, X_test, y_test, quant_type, filename):
    # # Create a TFLiteConverter instance
    # converter = tf.lite.TFLiteConverter.from_keras_model(model)

    # # Ensure LSTM compatibility
    # converter.target_spec.supported_ops = [
        # tf.lite.OpsSet.TFLITE_BUILTINS,
        # tf.lite.OpsSet.SELECT_TF_OPS
    # ]
    # converter._experimental_lower_tensor_list_ops = False
    # converter.experimental_enable_resource_variables = True

    # # Step 1: Apply quantization settings
    # if quant_type == 'int8':
        # # Define representative dataset generator
        # # Set inference_input_type and inference_output_type to tf.int8
        # # Enable default optimizations

        # # <-- Enter your code here <--#
        # pass

    # elif quant_type == 'float16':
        # # Enable default optimizations
        # # Set target_spec.supported_types to [tf.float16]

        # # <-- Enter your code here <--#
        # pass

    # elif quant_type == 'dynamic':
        # # Enable default optimizations

        # # <-- Enter your code here <--#
        # pass

    # # Step 2: Convert and save the model to `filename`

    # # <-- Enter your code here <--#

    # # Step 3: Run inference using the TFLite interpreter
    # # - Allocate tensors
    # # - Handle quantized input/output as needed
    # # - Collect model predictions (use dequantization if applicable)

    # # <-- Enter your code here <--#

    # # Step 4: Return model size and R² scores (overall + per feature)
    # # Hint: Use r2_score from sklearn

    # # <-- Enter your code here <--#

# # Step 5: Use the function above to create and evaluate three quantized models:
# # - 'int8' → save as 'model_int8.tflite'
# # - 'float16' → save as 'model_float16.tflite'
# # - 'dynamic' → save as 'model_dynamic.tflite'
# # For each quantized model Print out:
# # - Model name
# # - Size in KB
# # - Overall R²
# # - Per-feature R² for each feature (Feature 1, Feature 2, ..., etc.)

# # <-- Enter your code here <--#

# """## Problem 2 - Part (c)

# ### Pruning
# """

# # Step 1: Create a PolynomialDecay schedule that gradually increases sparsity during training.
# # Define a pruning schedule with:
# # - initial_sparsity = 0.5
# # - final_sparsity = 0.8
# # - end_step based on number of training steps (hint: dataset size / batch size * epochs)

# # <-- Enter your code here <--#

# # Step 2: Build a Functional model with:
# # - Input layer
# # - LSTM(64, relu)
# # - Dense(32, relu) [pruned]
# # - Dense(output_dim, linear) [pruned]
# # HINT: Wrap both Dense layers with prune_low_magnitude(...) using the schedule

# # <-- Enter your code here <--#

# # Step 3: Compile and train the model
# # - Use 'adam' and 'mse'
# # - Add tfmot.sparsity.keras.UpdatePruningStep() to callbacks
# # - Train the pruned model for 15 epochs and include the pruning callback.

# # <-- Enter your code here <--#

# # Step 4: Finalize the pruned model before exporting it to TFLite
# # Do any necessary post-processing (if needed) before exporting the model.

# # <-- Enter your code here <--#

# # Step 5: Export the model to TFLite format
# # - Use compression optimizations suitable for sparsity-aware models
# # - Save as "model_pruned.tflite"
# # - Print model size in KB

# # <-- Enter your code here <--#

# # Step 6: Predict using the finalized model (not the TFLite version)
# # - Use r2_score to compute overall and feature-wise performance

# # <-- Enter your code here <--#

# """## Problem 2 - Part (d)

# ### Knowledge Distillation
# """

# # Step 1: Generate soft predictions on X_train using LSTM model trained in Part (a) of Problem 2

# # <-- Enter your code here <--#

# # Step 2: Define the student model:
# # - LSTM(32, relu)
# # - Dense(16, relu)
# # - Dense(output_dim)

# # <-- Enter your code here <--#

# # Step 3: Define distillation_loss(y_true_combined, y_pred)
# # - y_true_combined contains both y_train and teacher_preds (concatenated)
# # - Compute MSE for hard and soft labels
# # - Use weighted average with alpha = 0.5

# # <-- Enter your code here <--#

# # Step 4: Concatenate y_train and teacher_preds along axis=1

# # <-- Enter your code here <--#

# # Step 5: Compile and train the student model for 10 epochs
# # - Use batch_size=32 and validation_split=0.1

# # <-- Enter your code here <--#

# # Step 6: Convert the student model to TFLite and save as "student_model.tflite"
# # - Ensure proper support for LSTM ops
# # - Compute and print TFLite file size for the student model (in KB)

# # <-- Enter your code here <--#

# # Step 7: Predict using the student model on X_test and Print summary of student model performance
# # - Compute overall R²
# # - Compute per-feature R² scores

# # <-- Enter your code here <--#

# """## Problem 2 - Part (e)

# ### Possibility of Further Model Size Reduction

# Can you **further reduce the model size** beyond the smallest model obtained in parts **(b)**, **(c)**, or **(d)**, **without sacrificing significant regression performance**?

# Your task is to:

# 1. **Analyze and compare** the results from previous parts: Which model had the smallest size? Which performed best?

# 2. **Propose a strategy** that combines or enhances techniques learned so far.

# 3. **Implement** your proposed solution.

# 4. **Evaluate** the resulting model using both:
   # - TFLite model size (in KB)
   # - Regression performance (overall $R^2$ value and feature-wise $R^2$ values)

# 5. **Justify your results:**
   # - If further size reduction is **not** possible without major loss of $R^2$ value, explain why using evidence from your experiments.
   # - If you succeed in reducing the size **further**, highlight what change made the biggest difference.

# """

# # <-- Justify your answer and if needed enter your code here <--#
