# -*- coding: utf-8 -*-
"""EE564_TinyML_Spring25_HW1_StudentVersion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U8PS9Lpp-2Z3XSDiEiigln_6OwvrDCuu
"""

# ~ !pip uninstall -y keras tensorflow tensorflow-model-optimization
# ~ !pip install tensorflow==2.12 tensorflow-model-optimization

# ============================
# Set backend early
# ============================
import os
os.environ["KERAS_BACKEND"] = "tensorflow"

# ============================
# Import libraries
# ============================
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report, confusion_matrix, r2_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import Input, Model

import tensorflow_model_optimization as tfmot

from pathlib import Path


# """## Problem 1 - Part (e)

# ### Possibility of Further Model Size Reduction

# Can you **further reduce the model size** beyond the smallest model obtained in parts **(b)**, **(c)**, or **(d)**, **without sacrificing significant classification performance**?

# Your task is to:

# 1. **Analyze and compare** the results from previous parts: Which model had the smallest size? Which performed best?

# 2. **Propose a strategy** that combines or enhances techniques learned so far.

# 3. **Implement** your proposed solution.

# 4. **Evaluate** the resulting model using both:
   # - TFLite model size (in KB)
   # - Classification performance (accuracy and report)

# 5. **Justify your results:**
   # - If further size reduction is **not** possible without major loss of accuracy, explain why using evidence from your experiments.
   # - If you succeed in reducing the size **further**, highlight what change made the biggest difference.

# """

# # <-- Justify your answer and if needed enter your code here <--#

# """

# ---


# Problem 2"""

# Load dataset


dataset_url = "file://" + os.path.abspath("./AirQualityUCI.csv")
ds_name = "airqual-data"
archive = tf.keras.utils.get_file(fname=ds_name, origin=dataset_url, extract=False)
data_dir = Path(archive).parent
ds_home = Path.home().joinpath(".keras/datasets")
assert data_dir==ds_home, "expect that ds is extracted under ~/.keras/dataset"

df = pd.read_csv(archive, sep=";", decimal=",", skipfooter=1, engine="python")
df = df.drop(columns=["Unnamed: 15", "Unnamed: 16"])
df["Datetime"] = pd.to_datetime(df["Date"] + " " + df["Time"], format="%d/%m/%Y %H.%M.%S")
df = df.drop(columns=["Date", "Time"])
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = df[col].str.replace(',', '.').astype("float32")
df.dropna(inplace=True)

# Number of data columns (excluding the Date Time column)
num_cols = df.shape[1]
print("Number of columns:", num_cols)

# Basic stats: min, max, mean, std
col_stats = df.describe().T[['min', 'max', 'mean', 'std']]
print("\nColumn statistics:\n", col_stats)

"""## Problem 2 - Part (a)
### Base Model Training and Evaluation
"""

# Step 1: Drop the 'Datetime' column and scale all remaining features to [0, 1]
X_excludedt = df.drop(columns=["Datetime"])
scaler = MinMaxScaler(feature_range=(0,1))
X_remain_norm = scaler.fit_transform(X_excludedt)

# Step 2: Implement create_sequences_all_to_all(data, seq_length) function
# - Output shape of X should be (num_sequences, 24, num_features)
# - Output shape of y should be (num_sequences, num_features)
# HINTs:
# Function should generate sequences of length 24, where:
#     - Each input sequence X[i] is a 24-time-step window
#     - The corresponding label y[i] is the value of all features at time step i + 24

# see for help (https://peyrone.medium.com/easy-guide-to-forcast-air-quality-with-lstm-c8596aeb5814)
# also (https://medium.com/@abimanyuiiba11/time-series-air-quality-prediction-using-long-short-term-memory-lstm-dce261dc4b80)
def create_sequences_all_to_all(data, seq_length):
    X, y = [], []
    for i in range(len(data) - seq_length):
        X.append(data[i:i + seq_length])
        y.append(data[i + seq_length])
    return np.array(X), np.array(y)


# Step 3: Perform an 80/20 train-test split
X, y = create_sequences_all_to_all(X_remain_norm, 24)
####print(X.shape) # seeeing (9333, 24, 13)
####print(y.shape) # seeeing (9333, 13)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 4: Build, Compile, and Train the LSTM model
# - Create a Keras Sequential model with:
#     - LSTM(64, relu)
#     - Dense(32, relu)
#     - Dense(output_dim = number of features)
# - Use 'adam' optimizer and 'mse' loss
# - Train for 10 epochs with batch_size=32 and validation_split=0.1
count_features = X.shape[2]
####print(count_features)
model = Sequential(
    [
        Input(shape=(X_train.shape[1], X_train.shape[2])),
        LSTM(64, activation="relu"),
        Dense(32, activation="relu"),
        Dense(count_features),
    ])
model.compile(optimizer='adam', loss='mse')
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.1)

# Step 5: Evaluate model using r2_score
# - Print overall R² and per-feature R²
# - Use model.predict() on X_test
y_pred = model.predict(X_test)
print(f"Overall R²: {r2_score(y_test, y_pred)}")

# Step 6: Convert and save the trained model to TFLite using float32 precision
# - Use TFLITE_BUILTINS and SELECT_TF_OPS
# - Save as 'model_float32.tflite'
# - Print model size
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,
    tf.lite.OpsSet.SELECT_TF_OPS
]
converter.target_spec.supported_types = [tf.float32]
tflite_model = converter.convert()
with open("model_float32.tflite", "wb") as f:
    f.write(tflite_model)

print(f"model_float32.tflite: {os.path.getsize('model_float32.tflite') / 1024:.2f} KB")

# """## Problem 2 - Part (b)

# ### Quantization (int8, float16, dynamic range)
# """

# def convert_and_evaluate(model, X_test, y_test, quant_type, filename):
    # # Create a TFLiteConverter instance
    # converter = tf.lite.TFLiteConverter.from_keras_model(model)

    # # Ensure LSTM compatibility
    # converter.target_spec.supported_ops = [
        # tf.lite.OpsSet.TFLITE_BUILTINS,
        # tf.lite.OpsSet.SELECT_TF_OPS
    # ]
    # converter._experimental_lower_tensor_list_ops = False
    # converter.experimental_enable_resource_variables = True

    # # Step 1: Apply quantization settings
    # if quant_type == 'int8':
        # # Define representative dataset generator
        # # Set inference_input_type and inference_output_type to tf.int8
        # # Enable default optimizations

        # # <-- Enter your code here <--#
        # pass

    # elif quant_type == 'float16':
        # # Enable default optimizations
        # # Set target_spec.supported_types to [tf.float16]

        # # <-- Enter your code here <--#
        # pass

    # elif quant_type == 'dynamic':
        # # Enable default optimizations

        # # <-- Enter your code here <--#
        # pass

    # # Step 2: Convert and save the model to `filename`

    # # <-- Enter your code here <--#

    # # Step 3: Run inference using the TFLite interpreter
    # # - Allocate tensors
    # # - Handle quantized input/output as needed
    # # - Collect model predictions (use dequantization if applicable)

    # # <-- Enter your code here <--#

    # # Step 4: Return model size and R² scores (overall + per feature)
    # # Hint: Use r2_score from sklearn

    # # <-- Enter your code here <--#

# # Step 5: Use the function above to create and evaluate three quantized models:
# # - 'int8' → save as 'model_int8.tflite'
# # - 'float16' → save as 'model_float16.tflite'
# # - 'dynamic' → save as 'model_dynamic.tflite'
# # For each quantized model Print out:
# # - Model name
# # - Size in KB
# # - Overall R²
# # - Per-feature R² for each feature (Feature 1, Feature 2, ..., etc.)

# # <-- Enter your code here <--#

# """## Problem 2 - Part (c)

# ### Pruning
# """

# # Step 1: Create a PolynomialDecay schedule that gradually increases sparsity during training.
# # Define a pruning schedule with:
# # - initial_sparsity = 0.5
# # - final_sparsity = 0.8
# # - end_step based on number of training steps (hint: dataset size / batch size * epochs)

# # <-- Enter your code here <--#

# # Step 2: Build a Functional model with:
# # - Input layer
# # - LSTM(64, relu)
# # - Dense(32, relu) [pruned]
# # - Dense(output_dim, linear) [pruned]
# # HINT: Wrap both Dense layers with prune_low_magnitude(...) using the schedule

# # <-- Enter your code here <--#

# # Step 3: Compile and train the model
# # - Use 'adam' and 'mse'
# # - Add tfmot.sparsity.keras.UpdatePruningStep() to callbacks
# # - Train the pruned model for 15 epochs and include the pruning callback.

# # <-- Enter your code here <--#

# # Step 4: Finalize the pruned model before exporting it to TFLite
# # Do any necessary post-processing (if needed) before exporting the model.

# # <-- Enter your code here <--#

# # Step 5: Export the model to TFLite format
# # - Use compression optimizations suitable for sparsity-aware models
# # - Save as "model_pruned.tflite"
# # - Print model size in KB

# # <-- Enter your code here <--#

# # Step 6: Predict using the finalized model (not the TFLite version)
# # - Use r2_score to compute overall and feature-wise performance

# # <-- Enter your code here <--#

# """## Problem 2 - Part (d)

# ### Knowledge Distillation
# """

# # Step 1: Generate soft predictions on X_train using LSTM model trained in Part (a) of Problem 2

# # <-- Enter your code here <--#

# # Step 2: Define the student model:
# # - LSTM(32, relu)
# # - Dense(16, relu)
# # - Dense(output_dim)

# # <-- Enter your code here <--#

# # Step 3: Define distillation_loss(y_true_combined, y_pred)
# # - y_true_combined contains both y_train and teacher_preds (concatenated)
# # - Compute MSE for hard and soft labels
# # - Use weighted average with alpha = 0.5

# # <-- Enter your code here <--#

# # Step 4: Concatenate y_train and teacher_preds along axis=1

# # <-- Enter your code here <--#

# # Step 5: Compile and train the student model for 10 epochs
# # - Use batch_size=32 and validation_split=0.1

# # <-- Enter your code here <--#

# # Step 6: Convert the student model to TFLite and save as "student_model.tflite"
# # - Ensure proper support for LSTM ops
# # - Compute and print TFLite file size for the student model (in KB)

# # <-- Enter your code here <--#

# # Step 7: Predict using the student model on X_test and Print summary of student model performance
# # - Compute overall R²
# # - Compute per-feature R² scores

# # <-- Enter your code here <--#

# """## Problem 2 - Part (e)

# ### Possibility of Further Model Size Reduction

# Can you **further reduce the model size** beyond the smallest model obtained in parts **(b)**, **(c)**, or **(d)**, **without sacrificing significant regression performance**?

# Your task is to:

# 1. **Analyze and compare** the results from previous parts: Which model had the smallest size? Which performed best?

# 2. **Propose a strategy** that combines or enhances techniques learned so far.

# 3. **Implement** your proposed solution.

# 4. **Evaluate** the resulting model using both:
   # - TFLite model size (in KB)
   # - Regression performance (overall $R^2$ value and feature-wise $R^2$ values)

# 5. **Justify your results:**
   # - If further size reduction is **not** possible without major loss of $R^2$ value, explain why using evidence from your experiments.
   # - If you succeed in reducing the size **further**, highlight what change made the biggest difference.

# """

# # <-- Justify your answer and if needed enter your code here <--#
